//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dolaris.UnitConverter.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dolaris.UnitConverter.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration is the rate of change of velocity..
        /// </summary>
        internal static string AccelerationDescription {
            get {
                return ResourceManager.GetString("AccelerationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An angle is the figure formed by two rays sharing a common endpoint..
        /// </summary>
        internal static string AngleDescription {
            get {
                return ResourceManager.GetString("AngleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area is the extent of a shape in the plane..
        /// </summary>
        internal static string AreaDescription {
            get {
                return ResourceManager.GetString("AreaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density is mass per unit volume..
        /// </summary>
        internal static string DensityDescription {
            get {
                return ResourceManager.GetString("DensityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Storage is a measure of the capacity of a system to store information..
        /// </summary>
        internal static string DigitalStorageDescription {
            get {
                return ResourceManager.GetString("DigitalStorageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy is the ability of a system to perform work and can be transferred from one object to another..
        /// </summary>
        internal static string EnergyDescription {
            get {
                return ResourceManager.GetString("EnergyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency is the number of repeating events per unit of time..
        /// </summary>
        internal static string FrequencyDescription {
            get {
                return ResourceManager.GetString("FrequencyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fuel economy of a vehicle is the relationship between distance traveled and fuel consumed..
        /// </summary>
        internal static string FuelEconomyDescription {
            get {
                return ResourceManager.GetString("FuelEconomyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length is any quantity with dimension distance..
        /// </summary>
        internal static string LengthDescription {
            get {
                return ResourceManager.GetString("LengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass is a measure of resistance to acceleration of a physical body when a force is applied..
        /// </summary>
        internal static string MassDescription {
            get {
                return ResourceManager.GetString("MassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power is the amount of energy consumed per unit of time when doing work..
        /// </summary>
        internal static string PowerDescription {
            get {
                return ResourceManager.GetString("PowerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure is the force applied to the surface of an area..
        /// </summary>
        internal static string PressureDescription {
            get {
                return ResourceManager.GetString("PressureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed is the velocity of an object. According to the theory of relativity, the fasted possible speed is the speed of light..
        /// </summary>
        internal static string SpeedDescription {
            get {
                return ResourceManager.GetString("SpeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature is a comparative measurement of hot or cold. The coldest temperature is zero degrees Kelvin..
        /// </summary>
        internal static string TemperatureDescription {
            get {
                return ResourceManager.GetString("TemperatureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is a sequence of events that occur in irreversible succession..
        /// </summary>
        internal static string TimeDescription {
            get {
                return ResourceManager.GetString("TimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume is the quantity of three-dimensional space enclosed by a closed surface..
        /// </summary>
        internal static string VolumeDescription {
            get {
                return ResourceManager.GetString("VolumeDescription", resourceCulture);
            }
        }
    }
}
